In [1]:
from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from astropy import units as u
from astropy.coordinates import SkyCoord

#comment out the next two lines if you do not have astroquery installed
#from astroquery.sdss import SDSS
#from astroquery.vizier import Vizier

from astropy.table import Table, Column, join
import pandas as pd

In [2]:
GOODS_TRANSLATE = Table.read('GOODSN_plus_translation_all.txt', format='ascii')#the GOODS Translate file is supposed 
#to contain an Index generated by Rebecca Larson's code. Her code scans the field and looks for emission line spikes. 
#That Index is unique to the date she used her code on it could be specific to the field she had her code analyze. 
#This is not a universal Index. The Translate file contains a column called "Steves_ID" which is supposed to be the 
#Index Dr. Finkelstein stores it by in his own more comprehensive catalogue. 

#I really hate that the second row is explicitly stating what kind of object is contained in each column. This is 
#useful information, but I don't need to know that right now. Probably a relic from INL or whatever it's called

CGS1_LINES = Table.read('CGS1_lines.txt', format='ascii') #really just taking a stab in the dark as to whether or not 
#this file is the one I need. It has a lot of data organized in one place, whereas much of the other .txt files 
#contained on the drive given to me by rebecca are disparate. There are hundreds of folders on that drive, and if 
#each one is its own singular emission source then there has been a major misunderstanding about what I am doing...

In [3]:
#let's make the translate file a pandas file as well so that we can easily merge it
TransPD = GOODS_TRANSLATE.to_pandas()
Translate = TransPD.set_index('Steves_ID') #i don't want Python to index this from zero...I may get rid of this line 
#later idk
Translate

ID          ra        dec             x             y
Steves_ID                                                               
z4_GND_22332    20029  189.179694  62.240789  11707.786000  10374.013000
z4_GND_19891    21567  189.265962  62.247546   9297.237000  10779.229000
z4_GND_14785    24413  189.164208  62.261807  12139.289000  11635.503000
z4_GND_41377    33402  189.208982  62.311845  10888.025000  14636.981000
z4_GND_819       3777  189.297333  62.154039   8414.783000   5169.538000
z4_GND_39165     9207  189.184421  62.188214  11577.835000   7219.417000
z4_GND_44202    30073  189.232273  62.290575  10238.617000  13360.706000
z4_GND_12864    25624  189.134321  62.267528  12973.424000  11979.763000
z4_GND_41287    33383  189.195998  62.312141  11249.994000  14654.882000
z4_GND_29320    15884  189.152002  62.220837  12483.067000   9177.656000
z4_GND_12477    25864  189.134577  62.268622  12966.180000  12045.393000
z4_GND_18876    21996  189.123195  62.250733  13285.710000  10972.553000
z4_GND_3077      6626  189.296943  62.174063   8427.000000   6370.991000
z4_GND_44672    28939  189.279634  62.284464   8916.985000  12994.556000
z4_GND_1924      5284  189.252485  62.165550   9671.958000   5859.311000
z4_GND_22271    20062  189.248591  62.241082   9782.441000  10391.175000
z4_GND_743       3654  189.275336  62.152778   9031.208000   5093.351000
z4_GND_24650    18709  189.379007  62.234207   6137.000000   9983.495000
z4_GND_18788    22046  189.371791  62.250883   6340.911000  10983.604000
z4_GND_8138     29630  189.280668  62.288209   8888.308000  13219.281000
z4_GND_1454      4741  189.251183  62.161023   9708.322000   5587.672000
z4_GND_9199     28328  189.157384  62.281529  12328.562000  12819.015000
z4_GND_8027     29850  189.279748  62.289345   8914.024000  13287.415000
z4_GND_42650    32275  189.213604  62.304125  10759.273000  14173.758000
z4_GND_44788    28270  189.129825  62.281167  13097.708000  12798.310000
z4_GND_7109     31607  189.189920  62.299846  11419.900000  13917.292000
z4_GND_31654    14422  189.363963  62.213382   6554.867000   8733.070000
z4_GND_27826    16799  189.221406  62.225483  10542.236000   9455.146000
z4_GND_40732     7980  189.295652  62.181892   8463.622000   6840.665000
z4_GND_28492    16397  189.395869  62.223457   5663.999000   9339.646000
...               ...         ...        ...           ...           ...
z7_GND_27838  5427838  189.136180  62.225498  12925.110330   9457.904932
z7_GND_11401  5411401  189.186600  62.270905  11513.620994  12180.860601
z7_GND_30554  5430554  189.394010  62.217052   5715.002291   8955.206538
z7_GND_26428  5426428  189.223540  62.229614  10482.543202   9703.025676
z7_GND_10560  5410560  189.068630  62.275246  14806.402226  12446.459241
z7_GND_5028   5405028  189.194900  62.326973  11280.153800  15544.808032
z7_GND_19479  5419479  189.239760  62.248119  10029.291832  10813.346662
z7_GND_28453  5428453  189.150270  62.223705  12531.290305   9349.805492
z6_GNW_25971  5425971  189.334730  62.286125   7379.699719  13096.107198
z6_GNW_6554   5406554  189.137210  62.146313  12903.019505   4706.763649
z6_GNW_3153   5403153  189.106030  62.123947  13779.627105   3366.244484
z7_GNW_28182  5428182  189.510130  62.274639   2482.459202  12421.607817
z7_GNW_7284   5407284  189.036040  62.149914  15738.467158   4929.037831
z7_GNW_11595  5411595  188.965240  62.176491  17716.471662   6530.632533
z7_GND_41319  5441319  189.229720  62.302727  10309.851081  14089.801099
z7_GND_10402  5410402  189.179280  62.275894  11717.748921  12480.344807
z7_GND_18228  5418228  189.245270  62.252533   9875.418196  11078.219651
z7_GND_15330  5415330  189.310870  62.260448   8043.517282  11554.519001
z7_GND_9908   5409908  189.286930  62.277763   8713.029475  12592.692964
z7_GND_14124  5414124  189.135640  62.263874  12936.901949  11760.484483
z7_GND_21926  5421926  189.282960  62.242146   8822.043229  10455.577145
z7_GND_18770  5418770  189.097340  62.250954  14007.962552  10987.138263
z8_G

In [4]:
CGS1_LINES #we can see how Rebecca's line-finding code results look in this box
CGS1PD = CGS1_LINES.to_pandas()
#these are not labelled in the original file, so I'll have to do some 
#educated guessing as to what each column is
CGS1 = CGS1PD.set_index('col1') #i don't want Python to index this from zero...I may get rid of this line 
#later idk
CGS1

col2    col3      col4   col5          col6          col7  \
col1                                                                        
CGS1_43335_91     80   4.520   9998.03  13.05  8.241390e-20  1.823140e-20   
CGS1_42854_113    42   4.188   9053.32   3.95  2.189270e-17  5.227390e-18   
CGS1_43205_113    34   4.519   8853.64   5.24  3.859230e-17  8.539730e-18   
CGS1_43246_91     26   6.485   8640.84   2.81  1.147630e-16  1.769740e-17   
CGS1_43386_113    36   4.462   8900.73   3.77  3.598330e-17  8.064450e-18   
CGS1_43415_91     14   7.681   8339.00   1.70  2.016510e-16  2.625420e-17   
CGS1_43415_91     18   8.817   8438.33   0.98  2.028620e-16  2.300810e-17   
CGS1_43415_91     24   4.655   8593.89   5.53  9.607250e-17  2.063670e-17   
CGS1_44009_113     8  10.537   8188.39   0.98  3.522900e-16  3.343340e-17   
CGS1_44009_113    11   8.244   8264.99   2.54  2.450760e-16  2.972670e-17   
CGS1_43335_91     79   4.179  10099.20  12.14  4.301300e-20  1.029170e-20   
CGS1_43060_113    15   4.543   8375.96  12.55  4.581410e-19  1.008560e-19   
CGS1_43060_113    24   4.778   8600.89  12.81  6.384100e-19  1.336010e-19   
CGS1_43060_113    32   4.413   8824.88  12.15  3.026220e-19  6.857800e-20   
CGS1_43060_113    36   4.193   8927.02  13.26  3.828250e-19  9.130070e-20   
CGS1_43060_113    55   4.366   9426.26  11.58  2.779710e-19  6.367000e-20   
CGS1_43060_113    59   4.226   9522.62  12.09  2.124710e-19  5.027850e-20   
CGS1_43386_113    31   4.315   8900.96   4.06  4.056950e-17  9.402780e-18   
CGS1_43205_113    29   4.262   8855.70   5.69  4.026250e-17  9.447850e-18   
CGS1_42854_113    37   4.304   9053.87   4.20  2.394420e-17  5.562860e-18   
CGS1_43403_113    21   4.407   8521.05   4.86  6.642020e-17  1.507000e-17   
CGS1_43904_113    93   5.041  10316.30   3.32  2.476850e-17  4.913550e-18   
CGS1_44180_113     5   5.989   8131.14   4.94  2.341530e-16  3.910040e-17   
CGS1_44180_113    10   4.033   8240.15   3.02  1.290920e-16  3.201210e-17   
CGS1_43691_113     4   9.193   8089.75   2.09  2.212590e-16  2.406840e-17   
CGS1_44665_91     90   4.779  10241.50   3.17  1.638700e-17  3.429260e-18   
CGS1_44295_133    45   4.039   9099.76  13.02  4.190820e-20  1.037590e-20   
CGS1_43403_113    16   4.011   8523.08   6.02  6.324130e-17  1.576690e-17   
CGS1_43625_133     3   4.177   8074.18  13.59  2.313660e-19  5.539450e-20   
CGS1_43625_133    11   4.336   8301.60  11.94  2.333460e-19  5.381120e-20   
...              ...     ...       ...    ...           ...           ...   
CGS1_49787_113    34   4.127   8839.84   2.40  3.325830e-17  8.058730e-18   
CGS1_49742_133    51  11.056   9286.04   1.38  1.016720e-16  9.196160e-18   
CGS1_49742_133    56   4.079   9390.03   2.62  4.038310e-17  9.899260e-18   
CGS1_49440_113     5   6.114   8118.49   5.81  1.022820e-16  1.672980e-17   
CGS1_49440_113     8   8.266   8201.28   4.43  1.248530e-16  1.510410e-17   
CGS1_49788_113    31  21.325   8812.70   0.26  1.693170e-16  7.939990e-18   
CGS1_49466_113    28  12.899   8711.92   0.66  1.628540e-16  1.262540e-17   
CGS1_49466_113    33  16.394   8812.81   0.32  1.901950e-16  1.160170e-17   
CGS1_49466_113    28  13.431   8812.93   0.52  1.728230e-16  1.286710e-17   
CGS1_49896_91     30   8.364  10113.00   0.51  4.851760e-17  5.800690e-18   
CGS1_49896_91     64   6.602  10978.80   3.54  3.439540e-17  5.209980e-18   
CGS1_49904_113    87   5.592  10164.90   2.59  3.221810e-17  5.761780e-18   
CGS1_49904_113    82   4.460  10166.80   5.15  2.674850e-17  5.997880e-18   
CGS1_49836_113    65   4.293  10566.20   3.88  3.794900e-17  8.839920e-18   
CGS1_49466_133    18   9.515   8581.53   3.43  1.467570e-16  1.542400e-17   
CGS1_50176_133     5   4.503   8651.30  12.33  8.988750e-20  1.996320e-20   
CGS1_50176_133     9   4.453   8751.48  12.67  4.405540e-20  9.893770e-21   
CGS1_50176_133    13   4.073   8849.64  12.86  1.177600e-19  2.890900e-20   
CGS1_50045_113    11   4.196   8700.96  11.98  2.416570e-19  5.758980e-20   
CGS1_50082_1

In [5]:
GOODS_CAT_AT = Table.read('3DHST_GOODS.cat', format='ascii') #here is Dr. Finkelstein's catalogue. There must be at 
#least one common item of information between this and the translate file. i have to get this to a point where it's 
#readable and can be manipulated in Pandas

#the first major problem is that Dr. Finkelstein created about 15 rows at the top of the catalogue that describe 
#the columns, instead of writing out column names. Pandas does not enjoy interpreting this. I'll need to tell it to 
#name the columns.

#okay it really did not fucking like that. I'm guessing that reading it in Pandas did not work. rather than read in
#the goddamn file, it simply assigned every single row in that .cat file to one giant entry. in essence, there are
#no columns in the table...or rather, there is only one column, and that column contains all the information for
#each entry. I can't imagine how pandas could do this badly with a read-in.

GOODS_CAT_from_at = GOODS_CAT_AT.to_pandas() #it seemed to be reading it fine in astropy tables, so let's try to 
#simply convert it to Pandas from Astropy

#that worked!

GOODS_CAT_from_at.columns = ['3DHST ID','RA','DEC', 'Best Redshift','Redshift Type (1=spec,2=grism,3=phot)',
                  'Flux F606W (nJy)', 'Flux Error F606W (nJy)', 'Flux F814W (nJy)', 'Flux Error F814W (nJy)', 
                  'Flux F125W (nJy)', 'Flux Error F125W (nJy)', 'Flux F140W (nJy)', 'Flux Error F140W (nJy)', 
                  'Flux F160W (nJy)', 'Flux Error F160W (nJy)'] #needed to rename these columns

Catalogue = GOODS_CAT_from_at.set_index('3DHST ID') #We added this line so that Python will not auto-generate a new
#zero index for this catalogue

In [6]:
Catalogue#finally we will take a look at Dr. Finkelstein's catalogue as I have reworked it 
#into a Pandas table

RA        DEC  Best Redshift  \
3DHST ID                                         
1         189.145203  62.094013       -99.0000   
2         189.154861  62.094128       -99.0000   
3         189.150406  62.094280       -99.0000   
4         189.148468  62.095020       -99.0000   
5         189.154419  62.094681       -99.0000   
6         189.150589  62.095577       -99.0000   
7         189.147156  62.095276       -99.0000   
8         189.154892  62.095711       -99.0000   
9         189.141296  62.095791       -99.0000   
10        189.137115  62.096096         1.6385   
11        189.143341  62.096275       -99.0000   
12        189.144638  62.096832       -99.0000   
13        189.135651  62.096607         0.5263   
14        189.140533  62.097763         1.3233   
15        189.131439  62.097385         0.8140   
16        189.141541  62.097805         1.2129   
17        189.156662  62.097897       -99.0000   
18        189.140610  62.098179         2.7974   
19        189.154968  62.099106       -99.0000   
20        189.154083  62.099724       -99.0000   
21        189.139679  62.098724         2.1363   
22        189.156601  62.098831       -99.0000   
23        189.140411  62.098915         0.6933   
24        189.132477  62.099072         2.1944   
25        189.155365  62.099140       -99.0000   
26        189.138290  62.099125         2.9237   
27        189.154846  62.100105       -99.0000   
28        189.145004  62.099747         2.2413   
29        189.146118  62.100830         0.4127   
30        189.160828  62.099777       -99.0000   
...              ...        ...            ...   
50478      53.248383 -27.668489         1.3441   
50479      53.170277 -27.660542         4.6508   
50480      53.168079 -27.668707         0.2635   
50481      53.153858 -27.668308         1.1122   
50482      53.180786 -27.657753         0.7809   
50483      53.253281 -27.662077         4.5774   
50484      53.251919 -27.667246         3.6848   
50485      53.260979 -27.666645         0.0755   
50486      53.254417 -27.666962         5.3163   
50487      53.174728 -27.662376         0.4442   
50488      53.257366 -27.666319         0.5865   
50489      53.251732 -27.666496         2.9967   
50490      53.174557 -27.660570         1.5898   
50491      53.152832 -27.667112         1.3553   
50492      53.171650 -27.661419         1.0567   
50493      53.171947 -27.663914         0.5696   
50494      53.150692 -27.665449         0.7115   
50495      53.157280 -27.662193         1.4597   
50496      53.143982 -27.669867       -99.0000   
50497      53.149300 -27.665281         2.1296   
50498      53.173637 -27.660870         1.1125   
50499      53.168877 -27.666813         2.0136   
50500      53.261185 -27.666292         0.5798   
50501      53.154724 -27.668280         0.1011   
50502      53.168365 -27.664034         0.3345   
50503      53.256226 -27.668900         1.8668   
50504      53.254128 -27.666880         3.9020   
50505      53.172928 -27.666491         1.0218   
50506      53.153439 -27.667759         0.2207   
50507      53.259346 -27.667986         3.6691   

          Redshift Type (1=spec,2=grism,3=phot)  Flux F606W (nJy)  \
3DHST ID                                                            
1                                             3         -35944.73   
2                                             3         -35944.73   
3                                             3         -35944.73   
4                                             3         -35944.73   
5                                             3         -35944.73   
6                                             3         -35944.73   
7                                             3         -35944.73   
8                                             3         -35944.73   
9                                             3         -35944.73   
10                                            3            174.74   
11                                     

In [7]:
#Dr. Finkelstein seems to believe that there will be no way to identify these sources other than by their
#Right Ascension and Declination. He has asked me to write code that takes the RA and DEC from the Translate file,
#and check it for the least distance from the RA and DEC in the Catalogue. Within a tolerance of 0.5 arc seconds
#we should consider a match. I have been told that this can be optimized so that we do not check it against sources
#that are obviously far away. 

#What we are trying to accomplish here is very difficult. my code must take the RA & DEC from an entry in Translate
#check its distance against each entry of Catalogue, and determine which one has the least distance. Once it has
#determined what the least distant is, take the entry from Translate and merge it with the entry of Catalogue in a 
#new DataFrame. Then it must move on to the next entry of Translate and repeat this process, adding it as the next
#result in our new DataFrame.

#distance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))

#def distance(RA1, DEC1, RA2, DEC2): #okay now what am i supposed to write for the rest of this...
    #lat1, lon1, lat2, lon2 = map(np.deg2rad, [lat1, lon1, lat2, lon2]) ?????
   ##dlon = lon2 - lon1 ?????
    #a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2 ?????
    #c = 2 * np.arcsin(np.sqrt(a)) ?????
    #total_miles = MILES * c ?????
    #return total_miles ?????




#Catalogue['distance'] = Catalogue.apply(lambda row: distance(189.179694, 62.240789, row['RA'], row['DEC']), axis=1)
#https://github.com/s-heisler/pycon2017-optimizing-pandas
#https://engineering.upside.com/a-beginners-guide-to-optimizing-pandas-code-for-speed-c09ef2c6a4d6
#df['distance'] = haversine(40.671, -73.985, df['latitude'], df['longitude'])

#http://docs.astropy.org/en/stable/coordinates/matchsep.html#astropy-coordinates-matching

In [8]:
#from astropy.coordinates import SkyCoord as sky
#from astropy import units as u
#c = SkyCoord(ra=ra1*u.degree, dec=dec1*u.degree)
#catalog = SkyCoord(ra=ra2*u.degree, dec=dec2*u.degree)
#idx, d2d, d3d = c.match_to_catalog_sky(catalog)

#idx, sep, _ = target_c.match_to_catalog_sky(catalog_c) 

#http://docs.astropy.org/en/stable/coordinates/matchsep.html#astropy-coordinates-matching
#http://docs.astropy.org/en/stable/coordinates/index.html#convenience-methods

#Between this box and the one above it, I should be able to figure out a way to compare these fucking numbers
#GOODS_TRANSLATE
#GOODS_CAT_AT

#if i want to do this, i'll need to strip both of these tables down to just their RA and DEC columns

In [9]:
#idx, sep, _ = TRANSRA.match_coordinates_sky(GOODSRA) 
#this did not work. this would only work if TRANSRA and GOODSRA are SkyCoord objects. they are not. they are tables..

In [10]:
#Roadblocks everywhere. No one to help me solve these problems. Friday at 5 pm. Fuck this.

#Met with Andreia Carrillo, a grad student in the Astronomy Dept here, and we talked through building a "For-Loop"
#with a function to help me find my distances

TRANSRA = GOODS_TRANSLATE['ra'] #we've cut down the RA and DEC we want to compare to their discrete columns
TRANSDEC = GOODS_TRANSLATE['dec']  #this is going to allow us to compare them piecemeal. We're going to treat
GOODSRA = GOODS_CAT_AT['col2']  #the smaller table as our 'i' value, and check it in a loop against the larger
GOODSDEC = GOODS_CAT_AT['col3'] #table entry by entry

Matches = [] #this creates a blank table that we will be saving our findings in

for i in range(len(TRANSRA)):
        DISTANCE = np.sqrt(((GOODSRA-TRANSRA[i])*np.cos(GOODSDEC))**2 + (GOODSDEC-TRANSDEC[i])**2)
        
        CLOSEST = np.where(DISTANCE == np.min(DISTANCE))
        
        if np.min(DISTANCE) < 0.5:
            Matches.append(CLOSEST)
        
        else:
            Matches.append('False')

In [11]:
Matches #this information is fucking useless to me in the way that it's currently formatted

[(array([20028]),),
 (array([21566]),),
 (array([24412]),),
 (array([33401]),),
 (array([3776]),),
 (array([9206]),),
 (array([30072]),),
 (array([25623]),),
 (array([33382]),),
 (array([15883]),),
 (array([25863]),),
 (array([21995]),),
 (array([6625]),),
 (array([28938]),),
 (array([5283]),),
 (array([20061]),),
 (array([3653]),),
 (array([18708]),),
 (array([22045]),),
 (array([29629]),),
 (array([4740]),),
 (array([28327]),),
 (array([29849]),),
 (array([32274]),),
 (array([28269]),),
 (array([31606]),),
 (array([14421]),),
 (array([16798]),),
 (array([7979]),),
 (array([16396]),),
 (array([30745]),),
 (array([18664]),),
 (array([19579]),),
 (array([11039]),),
 (array([34821]),),
 (array([9746]),),
 (array([17393]),),
 (array([14644]),),
 (array([6974]),),
 (array([12423]),),
 (array([15167]),),
 (array([15697]),),
 (array([16623]),),
 (array([28428]),),
 (array([21472]),),
 (array([20977]),),
 (array([19164]),),
 (array([32406]),),
 (array([25700]),),
 (array([18090]),),
 (array([